modified a lot

diff --git a/install_vmware b/install_vmware
--- a/install_vmware
+++ b/install_vmware
@@ -1,7 +1,11 @@
 #!/bin/bash
 
+. ./log_append
+
+DIR=`pwd`
+
 # Downloads the vmware package
-cd /home/*/Downloads
+cd /home/`whoami`/Downloads
 wget https://download3.vmware.com/software/wkst/file/VMware-Workstation-Full-15.5.1-15018445.x86_64.bundle
 
 # Enables the bundle package to be executed
@@ -9,17 +13,9 @@ chmod +x VMware*
 # Executes the bundle package
 sudo ./VMware* --console --eulas-agreed --required
 
-# Displays license keys
-echo -e "license key:"
-echo FF35R-DLX13-48DRZ-66M5V-XQ294
-echo VY5DH-D0GE0-0814Z-AXZGT-Y3UA6
-echo AV102-05Y9H-M89MQ-5ZN79-MZHR4
-
-# Opens vmware and fills in the license key
-echo -e "\a"
-vmware
-
 # Removes the package if vmware is successfully installed
 [ $? -eq 0 ] && rm -f VMware*
 
-[ $? -eq 0 ] && echo "vmware installed" >> $LOG || echo "failed to install pycharm" >> $LOG
+cd $DIR
+
+[ $? -eq 0 ] && log-append "vmware installed" || log_append "failed to install pycharm"
diff --git a/ubuntu_init b/ubuntu_init
--- a/ubuntu_init
+++ b/ubuntu_init
@@ -1,24 +1,27 @@
 #!/bin/bash
 
+. ./log_append
+
 # Creates a log
-LOG="ubuntu_init_"`date`".log"
+LOG="ubuntu_init_"`date "+%m-%d"`".log"
 touch $LOG
+sudo chmod +x log_append
 
 # dash -> bash
-sudo dpkg-reconfigure dash && echo "dash -> bash done" >> $LOG || echo "dash -> bash failed" >> $LOG
-echo "" >> $LOG
+sudo dpkg-reconfigure dash && log_append "dash -> bash done" || log_append "dash -> bash failed"
+log_append ""
 
 # Removes games
-sudo apt-get -y --purge remove aisleriot gnome-mahjongg gnome-mines gnome-sudoku libgnome-games-support-1-3:amd64 libgnome-games-support-common && echo "games removed" >> $LOG || echo "failed to remove games" >> $LOG
-echo "" >> $LOG
+sudo apt-get -y --purge remove aisleriot gnome-mahjongg gnome-mines gnome-sudoku libgnome-games-support-1-3:amd64 libgnome-games-support-common && log_append "games removed" || log_append "failed to remove games"
+log_append ""
 
 # Changes the sources
 sudo cp /etc/apt/sources.list /etc/apt/sources.list.bcakup
 sudo sh -c "cat sources > /etc/apt/sources.list"
 sudo apt-get update
 sudo apt-get -y upgrade
-[ $? -eq 0 ] && echo "sources changed" >> $LOG || echo "failed to change sources" >> $LOG
-echo "" >> $LOG
+[ $? -eq 0 ] && log_append "sources changed" || log_append "failed to change sources"
+log_append ""
 
 # Installs services and software
 sh install_git
@@ -32,15 +35,22 @@ sh install_chrome
 sh install_typora
 
 sh install_baidu_net_disk
-sh install_pycharm
 sh install_vmware
+sh install_pycharm
 sh install_onedrive
 # onedrive: Automatic update
 systemctl --user enable onedrive
 systemctl --user start onedrive
-[ $? -eq 0 ] && echo "onedrive installed" >> $LOG || echo "failed to install onedrive" >> $LOG
+[ $? -eq 0 ] && log_append "onedrive installed" || log_append "failed to install onedrive"
 
-echo "" >> $LOG
+log_append ""
+
+# Creates a soft link for Bookmarks of chrome
+ln -s /home/`whoami`/.config/google-chrome/Default/Bookmarks "/home/"`whoami`"/OneDrive/Chrome bookmarks/ubuntu_bookmark/Bookmarks" && log_append "created a soft link for the bookmark of chrome" || log_append "failed to create a soft link for the bookmark of chrome"
+log_append ""
 
 # Installs python packages
 sh install_py_pkgs
+
+# Displays the ssh key
+cat ~/.ssh/id_rsa.pub
